services:
  postgres:
    image: postgres:16
    container_name: school_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d school_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: school_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: school_loader
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: school_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: scolarite
    volumes:
      - ./data:/app/data
    command: ["python", "scripts/load_data.py"]

volumes:
  postgres_data: